export const siteConfig = {
  name: "Limosud Cars",
  shortName: "Limosud",
  brand: "LIMOSUD CARS",
  logo: "/logo.png",
  /** Square logo with background — favicon, browser tab, Google search icon only */
  brandIcon: "/IMG_7271.JPG.jpeg",
  heroBanner: "/heroandnavbarimge.jpeg",
  description:
    "Louez une voiture à Dakhla avec Limosud Cars. Flotte premium, livraison aéroport, tarifs transparents et assistance 24h/24.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  apiUrl: process.env.NEXT_PUBLIC_API_URL ?? "https://api.limosudcars.com/api",
  adminUrl: process.env.NEXT_PUBLIC_ADMIN_URL ?? "http://localhost:3001/login",
  locale: "fr_FR",
  language: "fr",
  defaultTitle: "Limosud Cars — Louez des voitures de confiance",
  titleTemplate: "%s | Limosud Cars",
  keywords: [
    "location voiture Dakhla",
    "location de voiture Dakhla",
    "dakhla location voiture",
    "dakhla location",
    "agence location voiture Dakhla",
    "louer une voiture Dakhla",
    "location voiture aéroport Dakhla",
    "location voiture Dakhla prix",
    "location 4x4 Dakhla",
    "Limosud Cars",
    "limosudcars",
    "car rental Dakhla",
    "rent a car Dakhla",
    "alquiler coche Dakhla",
    "كراء السيارات الداخلة",
  ],
  twitterHandle: "",
  contactEmail: "contact@limosudcars.com",
  phone: "06 61 04 09 67",
  secondaryPhone: "06 55 75 09 46",
  address: "Hay alqods N10 - Dakhla",
} as const;
